name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444
        options: --shm-size=2g

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          
      - name: Update Composer dependencies
        run: composer update --prefer-dist --no-progress
          
      - name: Start PHP server
        run: |
          php -S localhost:8000 -t . &
          sleep 5
          curl -v http://localhost:8000
          
      - name: Verify services
        run: |
          netstat -tulpn
          curl -v http://localhost:4444/status
          
      - name: Run acceptance tests   
        run: vendor/bin/codecept run Acceptance -vv --debug                     