name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444
        options: --shm-size=2g

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          
      - name: Update Composer dependencies
        run: composer update --prefer-dist --no-progress
          
      - name: Start PHP server
        run: |
          php -S 0.0.0.0:8000 -t . &
          sleep 5

      - name: Update Acceptance.suite.yml
        run: |
          sed -i 's/host: '"'"'selenium'"'"'/host: '"'"'localhost'"'"'/' tests/Acceptance.suite.yml
          cat tests/Acceptance.suite.yml
          
      - name: Run acceptance tests
        run: vendor/bin/codecept run Acceptance -vv --debug                 