name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444
        options: --shm-size=2g
        env:
          SE_NODE_MAX_SESSIONS: 4
          SE_NODE_OVERRIDE_MAX_SESSIONS: true

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          
      - name: Update Composer dependencies
        run: composer update --prefer-dist --no-progress
          
      - name: Configure hosts
        run: |
          echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
          
      - name: Start PHP server
        run: |
          php -S host.docker.internal:8000 -t . &
          sleep 5
          
      - name: Run acceptance tests
        run: vendor/bin/codecept run Acceptance -vv --debug          