name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444
        options: --shm-size=2g

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          
      - name: Start PHP server
        run: php -S localhost:8000 &
          
      - name: Install dependencies
        run: composer install

      - name: Run acceptance tests
        run: vendor/bin/codecept run acceptance
