# # name: Acceptance Tests

# # on:
# #   push:
# #     branches: [ main ]
# #   pull_request:
# #     branches: [ main ]

# # jobs:
# #   test:
# #     runs-on: ubuntu-latest
    
# #     services:
# #       selenium:
# #         image: selenium/standalone-firefox:4.10.0
# #         ports:
# #           - 4444:4444
# #           - 7900:7900
# #         options: --shm-size=2g
# #         env:
# #           SE_NODE_SESSION_TIMEOUT: 30
# #           SE_START_XVFB: false

# #     steps:
# #       - uses: actions/checkout@v3
      
# #       - name: Setup PHP
# #         uses: shivammathur/setup-php@v2
# #         with:
# #           php-version: '8.1'
# #           tools: composer:v2
          
# #       - name: Update Composer dependencies
# #         run: composer update --prefer-dist --no-progress
          
# #       - name: Start PHP server
# #         run: |
# #           php -S 0.0.0.0:8885 -t . &
# #           sleep 5
          
# #       - name: Verify Selenium
# #         run: |
# #           curl --retry 10 --retry-delay 5 -v http://localhost:4444/status
          
# #       - name: Run acceptance tests
# #         run: vendor/bin/codecept run Acceptance -vv --debug


# name: Acceptance Tests

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
    
#     services:
#        selenium:
#         image: selenium/standalone-firefox:4.10.0
#         ports:
#           - 4444:4444
#           - 7900:7900
#         options: --shm-size=2g
#         env:
#           SE_NODE_SESSION_TIMEOUT: 30
#           SE_START_XVFB: false

#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Setup GeckoDriver
#         run: |
#           wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
#           tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
#           chmod +x geckodriver
#           sudo mv geckodriver /usr/local/bin/
#           geckodriver --version
      
#       - name: Setup PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '8.1'
#           tools: composer:v2
          
#       - name: Update Composer dependencies
#         run: composer update --prefer-dist --no-progress
          
#       - name: Start PHP server
#         run: |
#           php -S 0.0.0.0:8885 -t . &
#           sleep 5
          
#       - name: Run acceptance tests
#         run: vendor/bin/codecept run Acceptance -vv --debug

name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-firefox:latest # Use latest for best compatibility
        ports:
          - 4444:4444  # Selenium port
          - 7900:7900 # Optional VNC for debugging

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
      - name: Install Dependencies
        # run: composer install --no-progress
        run: composer update --prefer-dist --no-progress
      - name: Start PHP Server
        run: |
          php -S 0.0.0.0:8885 -t . & # Bind to all interfaces
          sleep 5 # Give the server time to start
      - name: Add host.docker.internal to /etc/hosts
        run: echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - name: Wait for Selenium
        run: |
          while ! nc -z localhost 4444; do sleep 1; done # Check Selenium availability      - name: Run Acceptance Tests
        run: vendor/bin/codecept run Acceptance -vv --debug
