name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444
        options: --shm-size=2g --network-alias selenium

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          firefox --version
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
          
      - name: Update Composer dependencies
        run: composer update --prefer-dist --no-progress
          
      - name: Start PHP server
        run: |
          php -S 0.0.0.0:8000 -t . &
          sleep 5
          netstat -tulpn | grep 8000
          curl -v http://127.0.0.1:8000
          
      - name: Wait for Selenium
        run: |
          timeout 60s bash -c 'while ! nc -z localhost 4444; do sleep 2; done'
          curl -v http://localhost:4444/status
          
      - name: Run acceptance tests with debug
        env:
          SELENIUM_HOST: selenium
          PHP_SERVER_HOST: 127.0.0.1
        run: |
          export DISPLAY=:99
          vendor/bin/codecept run acceptance -vv --debug